#!/bin/sh
#Point to the upstream
git remote add upstream https://github.com/precocious-tangerine/evercode
#Add everyone's remotes
git remote add edison https://github.com/bamboostgg/evercode
git remote add orlando https://github.com/orlandoc01/evercode
git remote add gerrit https://github.com/yntema/evercode
git remote add max https://github.com/maxkroshka/evercode
#Add shortcuts to everyone's remotes
git remote add u https://github.com/precocious-tangerine/evercode
git remote add e https://github.com/bamboostgg/evercode
git remote add o https://github.com/orlandoc01/evercode
git remote add g https://github.com/yntema/evercode
git remote add m https://github.com/maxkroshka/evercode

#Overwrite if existing
git remote set-url upstream https://github.com/precocious-tangerine/evercode
git remote set-url edison https://github.com/bamboostgg/evercode
git remote set-url orlando https://github.com/orlandoc01/evercode
git remote set-url gerrit https://github.com/yntema/evercode
git remote set-url max https://github.com/maxkroshka/evercode
git remote set-url u https://github.com/precocious-tangerine/evercode
git remote set-url e https://github.com/bamboostgg/evercode
git remote set-url o https://github.com/orlandoc01/evercode
git remote set-url g https://github.com/yntema/evercode
git remote set-url m https://github.com/maxkroshka/evercode