#!/bin/sh
#Point to the upstream
git remote add upstream https://www.github.com/precocious-tangerine/evercode
#Add everyone's remotes
git remote add edison https://www.github.com/bamboostgg/evercode
git remote add orlando https://www.github.com/orlandoc01/evercode
git remote add gerrit https://www.github.com/yntema/evercode
git remote add max https://www.github.com/maxkroshka/evercode
#Add shortcuts to everyone's remotes
git remote add u https://www.github.com/precocious-tangerine/evercode
git remote add e https://www.github.com/bamboostgg/evercode
git remote add o https://www.github.com/orlandoc01/evercode
git remote add g https://www.github.com/yntema/evercode
git remote add m https://www.github.com/maxkroshka/evercode