module.exports = {
	githubClientId: '',
	githubSecret: '',
	githubCallback: 'user/auth/github/callback',
	mongodbHost: 'mongodb://127.0.0.1',
	mongodbUsersName: '/neverCodeUsers',
	mongodbFilesName: '/neverCodeFiles',
	mongodbPort: ':27017',
	secretToken: '',
	verificationEmailRoute: 'user/email-verification',
	filesServerAddress: '',
	filesServerPort: undefined ,
	filesServerAddress: '',
	filesServerPort: '',
	userServerAddress: '',
	userServerPort: '',
	nginxServerAddress: '',
	nginxServerPort: '',
	urlDomain: '' 
};