module.exports.testSnippets = 	
[ { _createdAt: 'today',
    _updatedAt: 'now',
    createdBy: 'testuser',
    name: 'snippet1.txt',
    filePath: 'testuser/folder1/snippet1.txt',
    labels: 'important',
    sharUrl: 'not supported' },
  { _createdAt: 'today',
    _updatedAt: 'now',
    createdBy: 'testuser',
    name: 'snippet2.txt',
    filePath: 'testuser/snippet2.txt',
    labels: 'important',
    sharUrl: 'not supported' },
  { _createdAt: 'today',
    _updatedAt: 'now',
    createdBy: 'testuser',
    name: 'snippet3.txt',
    filePath: 'testuser/folder2/snippet3.txt',
    labels: 'important',
    sharUrl: 'not supported' },
  { _createdAt: 'today',
    _updatedAt: 'now',
    createdBy: 'testuser',
    name: 'snippet4.txt',
    filePath: 'testuser/folder1/subfolder1/snippet4.txt',
    labels: 'important',
    sharUrl: 'not supported' },
  { _createdAt: 'today',
    _updatedAt: 'now',
    createdBy: 'testuser',
    name: 'snippet5.txt',
    filePath: 'testuser/folder1/subfolder2/snippet5.txt',
    labels: 'important',
    sharUrl: 'not supported' },
  { _createdAt: 'today',
    _updatedAt: 'now',
    createdBy: 'testuser',
    name: '.config',
    filePath: 'testuser/.config',
    labels: 'important',
    sharUrl: 'not supported' },
  { _createdAt: 'today',
    _updatedAt: 'now',
    createdBy: 'testuser',
    name: '.config',
    filePath: 'testuser/folder1/.config',
    labels: 'important',
    sharUrl: 'not supported' },
  { _createdAt: 'today',
    _updatedAt: 'now',
    createdBy: 'testuser',
    name: '.config',
    filePath: 'testuser/folder2/.config',
    labels: 'important',
    sharUrl: 'not supported' },
  { _createdAt: 'today',
    _updatedAt: 'now',
    createdBy: 'testuser',
    name: '.config',
    filePath: 'testuser/folder1/subfolder1/.config',
    labels: 'important',
    sharUrl: 'not supported' },
  { _createdAt: 'today',
    _updatedAt: 'now',
    createdBy: 'testuser',
    name: '.config',
    filePath: 'testuser/folder1/subfolder2/.config',
    labels: 'important',
    sharUrl: 'not supported' } ];
    